# Generated by Django 4.2.16 on 2025-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('Exterior Wash', 'Exterior Wash'), ('Full Interior Cleaning', 'Full Interior Cleaning'), ('Car Detailing', 'Car Detailing')], max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
