# Generated by Django 4.2.16 on 2025-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
